{% set name = "sos-pbs" %}
{% set version = "0.20.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a296dfc9bcb228102c470f0b5ea881345f724e52b7fbcda382120e2b511fd3b

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - setuptools
    - sos >=0.17.0

test:
  imports:
    - sos_pbs

about:
  home: https://github.com/vatlab/SOS
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: PBS task engine for Script of Scripts (SoS)
  doc_url: https://vatlab.github.io/sos-docs/

extra:
  recipe-maintainers:
    - BoPeng
    - gaow
    - jdblischak
