{% set name = "sos-pbs" %}
{% set version = "0.20.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56f39c6eb96461df58cb492f209ede9ad5e2192b5922f12ae2610ac6a232ba1e

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - setuptools
    - sos >=0.17.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - sos_pbs

about:
  home: https://github.com/vatlab/SOS
  license: BSD-3-Clause
  license_file: LICENSE
  summary: PBS task engine for Script of Scripts (SoS)
  doc_url: https://vatlab.github.io/sos-docs/

extra:
  recipe-maintainers:
    - danielnachun
    - BoPeng
    - gaow
    - jdblischak
