{% set name = "sos-pbs" %}
{% set version = "0.20.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acfaca6394aa7473b2cd77698d21530c8b26a3c328dc4063a327c008578d1036

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - setuptools
    - sos >=0.17.0

test:
  imports:
    - sos_pbs

about:
  home: https://github.com/vatlab/SOS
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: PBS task engine for Script of Scripts (SoS)
  doc_url: https://vatlab.github.io/sos-docs/

extra:
  recipe-maintainers:
    - BoPeng
    - gaow
    - jdblischak
